---
# https://johnscs.com/remove-proxmox51-subscription-notice/
- name: Disable Proxmox License Warning
  become: True
  replace:
    path: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
    regexp: "data.status !== 'Active'"
    replace: "false"
    backup: yes
  register: license_warning

- name: Restart pveproxy.service
  become: True
  systemd:
    name: pveproxy.service
    state: restarted
  when: license_warning.changed

# https://pve.proxmox.com/pve-docs/pve-admin-guide.html#sysadmin_package_repositories
- name: Remove Enterprise Repo
  become: True
  lineinfile:
    path: "/etc/apt/sources.list.d/pve-enterprise.list"
    regex: "deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise"
    line: "#deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise"
    state: present

- name: Add Proxmox VE No-Subscription Repo
  become: True
  lineinfile:
    path: "/etc/apt/sources.list"
    line: "deb http://download.proxmox.com/debian/pve buster pve-no-subscription"
    state: present
    create: yes